import Foundation
import Observation

@Observable
@MainActor
final class CopilotService {
    private static let chatEndpoint = "https://api.githubcopilot.com/chat/completions"
    private static let responsesEndpoint = "https://api.githubcopilot.com/responses"
    private static let modelsEndpoint = "https://api.githubcopilot.com/models"
    private static let openCodeVersion = "1.0.0"
    private static let userAgent = "opencode/\(openCodeVersion)"
    private static let maxToolIterationsChat = 10
    private static let maxToolIterationsCoding = 50

    /// GPT models use Responses API; others (Claude, etc.) use Chat Completions.
    private static func useResponsesAPI(model: String) -> Bool {
        let m = model.lowercased()
        return m.hasPrefix("gpt") || m.hasPrefix("o1") || m.hasPrefix("o3") || m.hasPrefix("o4")
    }

    private static let urlSession: URLSession = {
        let config = URLSessionConfiguration.default
        config.timeoutIntervalForRequest = 180
        config.timeoutIntervalForResource = 600
        return URLSession(configuration: config, delegate: nil, delegateQueue: OperationQueue())
    }()

    var messages: [ChatMessage] = []
    var isStreaming = false
    var streamingError: String?
    /// Incremented on every streaming content delta — cheap scroll trigger.
    var contentRevision: Int = 0
    var availableModels: [ModelsResponse.ModelInfo] = []
    var toolCallStatuses: [String: ToolCallStatus] = [:]
    var toolCallServerNames: [String: String] = [:]
    var tokenUsage: TokenUsage?
    var isCompacting = false
    var summaryMessageId: UUID?

    /// Tool names discovered via tool_search in the current conversation (for deferred loading mode).
    var discoveredMCPTools: Set<String> = []

    // Permission flow
    private var permissionContinuation: CheckedContinuation<PermissionDecision, Never>?

    // MARK: - Context Window

    private var selectedModelInfo: ModelsResponse.ModelInfo? {
        availableModels.first { $0.id == settingsStore.selectedModel }
    }

    var contextWindow: Int {
        // Copilot API: exact prompt limit (most accurate for Copilot provider)
        if let copilotInfo = selectedModelInfo?.maxPromptTokens, copilotInfo > 0 {
            return copilotInfo
        }
        // models.dev: synchronous in-memory lookup (works for all providers)
        if let registry = providerRegistry,
           let modelInfo = registry.activeModelInfo() {
            return modelInfo.contextWindow
        }
        return Self.defaultContextWindow
    }

    /// Get context window from models.dev (async, for display purposes).
    func modelsDevContextWindow() async -> Int? {
        guard let modelInfo = await providerRegistry?.activeModelInfo() else { return nil }
        return modelInfo.contextWindow
    }

    /// Auto-generated title for the current conversation (set after first response).
    var autoGeneratedTitle: String?
    private var titleGenerationTask: Task<Void, Never>?

    private let authManager: AuthManager
    private let settingsStore: SettingsStore
    private(set) var providerRegistry: ProviderRegistry?
    private var streamTask: Task<Void, any Error>?

    init(authManager: AuthManager, settingsStore: SettingsStore) {
        self.authManager = authManager
        self.settingsStore = settingsStore
    }

    /// Set the provider registry (called from app init after registry is created).
    func setProviderRegistry(_ registry: ProviderRegistry) {
        self.providerRegistry = registry
    }

    /// Resolve the current LLM provider from the registry.
    /// Only falls back to built-in CopilotProvider when Copilot is the active provider.
    private func resolveProvider() -> (any LLMProvider)? {
        let activeId = providerRegistry?.activeProviderId ?? "github-copilot"
        if let registry = providerRegistry, let provider = registry.activeProvider() {
            return provider
        }
        // Only fall back to Copilot if that's what the user selected
        if activeId == "github-copilot", authManager.isAuthenticated {
            return CopilotProvider(tokenProvider: { [weak authManager] in
                await MainActor.run { authManager?.token }
            })
        }
        // Non-Copilot provider failed to resolve — don't silently switch
        return nil
    }

    /// Get the current model ID — from registry if available, otherwise from settings.
    private var currentModelId: String {
        if let registry = providerRegistry, !registry.activeModelId.isEmpty {
            return registry.activeModelId
        }
        return settingsStore.selectedModel
    }

    // MARK: - Chat

    func sendMessage(_ content: String, imageData: Data? = nil, tools: [MCPTool] = []) {
        let userMessage = ChatMessage(role: .user, content: content, imageData: imageData)
        messages.append(userMessage)
        startCompletionLoop(tools: tools)
    }

    func editAndResend(_ messageId: UUID, newContent: String, tools: [MCPTool] = []) {
        stopStreaming()
        guard let index = messages.firstIndex(where: { $0.id == messageId }) else { return }
        truncateMessages(from: index)
        sendMessage(newContent, tools: tools)
    }

    func regenerateLastResponse(tools: [MCPTool] = []) {
        stopStreaming()
        guard let lastUserIndex = messages.lastIndex(where: { $0.role == .user }) else { return }
        truncateMessages(from: lastUserIndex + 1)
        startCompletionLoop(tools: tools)
    }

    private func truncateMessages(from index: Int) {
        guard index < messages.count else { return }
        for msg in messages[index...] {
            if let calls = msg.toolCalls {
                for call in calls {
                    toolCallStatuses.removeValue(forKey: call.id)
                    toolCallServerNames.removeValue(forKey: call.id)
                }
            }
        }
        messages.removeSubrange(index...)
        if let sid = summaryMessageId, !messages.contains(where: { $0.id == sid }) {
            summaryMessageId = nil
        }
    }

    func retryToolCall(_ call: ToolCall, tools: [MCPTool] = []) {
        // Remove the previous failed tool result to avoid duplicate toolCallIds
        messages.removeAll { $0.role == .tool && $0.toolCallId == call.id }
        runStreamingTask {
            await self.executeSingleToolCall(call)
            let next = ChatMessage(role: .assistant, content: "")
            self.messages.append(next)
            try await self.completionLoop(startingAt: self.messages.count - 1, tools: tools)
        }
    }

    func stopStreaming() {
        streamTask?.cancel()
        streamTask = nil
        isStreaming = false
    }

    func newConversation() {
        stopStreaming()
        // Resume any pending permission prompt so the continuation isn't leaked
        permissionContinuation?.resume(returning: .deny)
        permissionContinuation = nil
        messages.removeAll()
        toolCallStatuses.removeAll()
        toolCallServerNames.removeAll()
        tokenUsage = nil
        summaryMessageId = nil
        discoveredMCPTools.removeAll()
        autoGeneratedTitle = nil
        titleGenerationTask?.cancel()
        titleGenerationTask = nil
        settingsStore.clearSessionPermissions()
    }

    func resolvePermission(_ decision: PermissionDecision) {
        permissionContinuation?.resume(returning: decision)
        permissionContinuation = nil
    }

    /// Load messages from a saved conversation (for resuming).
    func loadMessages(_ saved: [ChatMessage], summaryMessageId: UUID? = nil) {
        stopStreaming()
        messages = saved
        self.summaryMessageId = summaryMessageId
        toolCallStatuses.removeAll()
        toolCallServerNames.removeAll()
        discoveredMCPTools.removeAll()
        // Restore tool call statuses — mark all as completed since they're from a saved session
        // Also rebuild discoveredMCPTools from tool_search history
        for msg in saved where msg.role == .assistant {
            if let calls = msg.toolCalls {
                for call in calls {
                    toolCallStatuses[call.id] = .completed
            if call.function.name == "tool_search" {
                let (query, maxResults) = Self.parseToolSearchArgs(call.function.arguments)
                let (resultText, matchedNames) = PluginRegistry.shared.searchTools(
                    query: query, maxResults: maxResults, in: settingsStore.mcpTools
                )
                        discoveredMCPTools.formUnion(matchedNames)
                    }
                }
            }
        }
    }

    // MARK: - Completion Loop

    private static let maxRetries = 3
    private static let baseRetryDelay: TimeInterval = 2.0
    private static let maxRetryDelay: TimeInterval = 30.0

    private func runStreamingTask(_ work: @escaping @MainActor () async throws -> Void) {
        guard !isStreaming else { return }
        isStreaming = true
        streamingError = nil
        streamTask = Task {
            do {
                try await work()
            } catch is CancellationError {
            } catch {
                streamingError = error.localizedDescription
                let idx = messages.count - 1
                if idx >= 0, messages[idx].role == .assistant {
                    if messages[idx].content.isEmpty {
                        messages[idx].content = "Error: \(error.localizedDescription)"
                    } else {
                        messages[idx].finishReason = .error
                    }
                }
            }
            isStreaming = false
        }
    }

    private func withRetry(_ operation: @escaping @MainActor () async throws -> Void) async throws {
        var lastError: Error?
        for attempt in 0..<Self.maxRetries {
            do {
                try await operation()
                return
            } catch is CancellationError {
                throw CancellationError()
            } catch let error as ProviderError {
                switch error {
                case .rateLimited(let retryAfter), .overloaded(let retryAfter):
                    if attempt == Self.maxRetries - 1 {
                        lastError = error
                        break
                    }
                    let rawDelay = retryAfter ?? (Self.baseRetryDelay * pow(2.0, Double(attempt)))
                    let delay = min(rawDelay, Self.maxRetryDelay)
                    try await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
                    continue
                default:
                    throw error
                }
            } catch {
                if isRetryableStreamError(error) {
                    if attempt == Self.maxRetries - 1 {
                        lastError = error
                        break
                    }
                    let delay = min(Self.baseRetryDelay * pow(2.0, Double(attempt)), Self.maxRetryDelay)
                    try await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
                    continue
                }
                throw error
            }
        }
        if let error = lastError { throw error }
    }

    private func isRetryableStreamError(_ error: Error) -> Bool {
        if let msg = (error as? LocalizedError)?.errorDescription {
            let lower = msg.lowercased()
            if lower.contains("overloaded")
                || lower.contains("rate limit")
                || lower.contains("too many requests")
                || lower.contains("429") {
                return true
            }
        }
        return false
    }

    private func startCompletionLoop(tools: [MCPTool]) {
        let assistantMessage = ChatMessage(role: .assistant, content: "")
        messages.append(assistantMessage)
        let assistantIndex = messages.count - 1
        runStreamingTask {
            try await self.completionLoop(startingAt: assistantIndex, tools: tools)
            // Auto-compact if context window is nearly full
            if self.shouldCompact {
                self.isCompacting = true
                defer { self.isCompacting = false }
                try await self.compactConversation()
            }
        }
    }

    private var shouldCompact: Bool {
        guard let usage = tokenUsage, contextWindow > 0 else { return false }
        return Double(usage.promptTokens) / Double(contextWindow) >= 0.95
    }

    private var maxToolIterations: Int {
        settingsStore.appMode == .coding ? Self.maxToolIterationsCoding : Self.maxToolIterationsChat
    }

    private func completionLoop(startingAt index: Int, tools: [MCPTool]) async throws {
        var currentIndex = index

        for _ in 0..<maxToolIterations {
            let streamIndex = currentIndex
            try await withRetry {
                try await self.streamCompletion(updatingAt: streamIndex, tools: tools)
            }

            messages[currentIndex].tokenUsage = tokenUsage

            guard let toolCalls = messages[currentIndex].toolCalls, !toolCalls.isEmpty else {
                break
            }

            try Task.checkCancellation()
            await executeToolCalls(toolCalls)

            try Task.checkCancellation()
            let nextAssistant = ChatMessage(role: .assistant, content: "")
            messages.append(nextAssistant)
            currentIndex = messages.count - 1
        }
    }

    private func executeToolCalls(_ calls: [ToolCall]) async {
        for call in calls {
            let serverName = settingsStore.serverNameForTool(call.function.name) ?? "Unknown"
            toolCallServerNames[call.id] = serverName
        }
        for call in calls {
            await checkAndExecuteToolCall(call)
        }
    }

    private func checkAndExecuteToolCall(_ call: ToolCall) async {
        let serverName = toolCallServerNames[call.id] ?? "Unknown"
        let check = settingsStore.checkPermission(toolName: call.function.name, serverName: serverName)

        switch check {
        case .allowed:
            toolCallStatuses[call.id] = .pending
            await executeSingleToolCall(call)
            return
        case .denied:
            toolCallStatuses[call.id] = .failed("Blocked by tool permission")
            messages.append(ChatMessage(
                role: .tool, content: "Tool call blocked by permission settings.",
                toolCallId: call.id, toolName: call.function.name
            ))
            return
        case .ask:
            break
        }

        toolCallStatuses[call.id] = .awaitingPermission
        assert(permissionContinuation == nil, "Permission continuation overwrite — previous prompt was not resolved")
        let decision = await withCheckedContinuation { (continuation: CheckedContinuation<PermissionDecision, Never>) in
            permissionContinuation = continuation
        }

        if case .deny = decision {
            toolCallStatuses[call.id] = .failed("Permission denied")
            messages.append(ChatMessage(
                role: .tool, content: "Tool call denied by user.",
                toolCallId: call.id, toolName: call.function.name
            ))
            return
        }

        if case .allowForChat = decision { settingsStore.allowServerForSession(serverName) }
        if case .allowAlways = decision { settingsStore.allowServerAlways(serverName) }
        toolCallStatuses[call.id] = .pending
        await executeSingleToolCall(call)
    }

    private static let fileSystemToolNames: Set<String> = [
        "list_files", "read_file", "write_file", "edit_file", "create_file", "delete_file", "move_file", "switch_mode"
    ]

    private func executeSingleToolCall(_ call: ToolCall) async {
        toolCallStatuses[call.id] = .executing
        do {
            let text: String
            var imageData: Data?

            if call.function.name == "tool_search" {
                let (query, maxResults) = Self.parseToolSearchArgs(call.function.arguments)
                let pluginTools = PluginRegistry.shared.allTools(for: settingsStore.appMode)
                let availableTools = pluginTools + settingsStore.mcpTools
                let (resultText, matchedNames) = PluginRegistry.shared.searchTools(
                    query: query, maxResults: maxResults, in: availableTools
                )
                discoveredMCPTools.formUnion(matchedNames)
                text = resultText
                imageData = nil
            } else if call.function.name == "switch_mode" {
                let newMode = Self.parseSwitchModeArgs(call.function.arguments)
                settingsStore.appMode = newMode
                if newMode == .coding && !WorkspaceManager.shared.hasWorkspace {
                    text = "Switched to coding mode. Please select a project folder to enable file operations."
                    await requestWorkspaceSelection()
                } else {
                    text = "Switched to \(newMode.label) mode."
                }
                imageData = nil
            } else if Self.fileSystemToolNames.contains(call.function.name) {
                if !WorkspaceManager.shared.hasWorkspace {
                    text = "No workspace selected. Please switch to coding mode and select a project folder first."
                    imageData = nil
                } else {
                    let pluginResult = try await executePluginTool(call.function.name, argumentsJSON: call.function.arguments)
                    text = pluginResult.text
                    imageData = pluginResult.imageData
                }
            } else if let pluginResult = try? await executePluginTool(call.function.name, argumentsJSON: call.function.arguments) {
                text = pluginResult.text
                imageData = pluginResult.imageData
            } else if call.function.name == "github_clone" {
                toolCallStatuses[call.id] = .pending
                let message = ChatMessage(
                    role: .tool, content: "Cloning repository…",
                    toolCallId: call.id, toolName: call.function.name
                )
                messages.append(message)
                let messageId = message.id
                do {
                    let finalResult = try await executePluginToolStreaming(
                        call.function.name,
                        argumentsJSON: call.function.arguments,
                        progressHandler: { [weak self] progress in
                            guard let self = self else { return }
                            MainActor.assumeIsolated {
                                if let idx = self.messages.firstIndex(where: { $0.id == messageId }) {
                                    self.messages[idx].toolProgress = progress
                                    self.contentRevision &+= 1
                                }
                            }
                        }
                    )
                    if let idx = messages.firstIndex(where: { $0.id == messageId }) {
                        messages[idx].content = finalResult.text
                        messages[idx].toolProgress = nil
                        messages[idx].imageData = finalResult.imageData
                    }
                    toolCallStatuses[call.id] = .completed
                } catch {
                    if let idx = messages.firstIndex(where: { $0.id == messageId }) {
                        messages[idx].content = "Error: \(error.localizedDescription)"
                        messages[idx].toolProgress = nil
                    }
                    toolCallStatuses[call.id] = .failed(error.localizedDescription)
                }
                return
            } else {
                text = try await settingsStore.callTool(
                    name: call.function.name,
                    argumentsJSON: call.function.arguments
                )
                imageData = nil
            }
            toolCallStatuses[call.id] = .completed
            messages.append(ChatMessage(
                role: .tool, content: text,
                toolCallId: call.id, toolName: call.function.name,
                imageData: imageData
            ))
        } catch {
            let errorMsg = error.localizedDescription
            toolCallStatuses[call.id] = .failed(errorMsg)
            messages.append(ChatMessage(
                role: .tool, content: "Error: \(errorMsg)",
                toolCallId: call.id, toolName: call.function.name
            ))
        }
    }

    private static func parseToolSearchArgs(_ argumentsJSON: String) -> (query: String, maxResults: Int) {
        guard let data = argumentsJSON.data(using: .utf8),
              let args = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let query = args["query"] as? String else {
            return ("", 5)
        }
        let maxResults = args["max_results"] as? Int ?? 5
        return (query, maxResults)
    }

    private static func parseSwitchModeArgs(_ argumentsJSON: String) -> AppMode {
        guard let data = argumentsJSON.data(using: .utf8),
              let args = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let modeStr = args["mode"] as? String,
              let mode = AppMode(rawValue: modeStr) else {
            return .chat
        }
        return mode
    }

    private func requestWorkspaceSelection() async {
        await MainActor.run {
            NotificationCenter.default.post(name: .requestWorkspaceSelection, object: nil)
        }
    }

    private func executePluginTool(_ name: String, argumentsJSON: String) async throws -> ToolResult {
        for (pluginId, hooks) in hooksMap {
            if hooks.tools.contains(where: { $0.name == name }) {
                return try await PluginRegistry.shared.executeTool(pluginId: pluginId, toolName: name, argumentsJSON: argumentsJSON)
            }
        }
        throw PluginRegistry.PluginError.unknownTool(name)
    }

    private func executePluginToolStreaming(
        _ name: String,
        argumentsJSON: String,
        progressHandler: @escaping @Sendable (String) -> Void
    ) async throws -> ToolResult {
        var foundId: String?
        for (pluginId, hooks) in hooksMap {
            for tool in hooks.tools {
                if tool.name == name {
                    foundId = pluginId
                    break
                }
            }
            if foundId != nil { break }
        }
        guard let id = foundId else {
            throw PluginRegistry.PluginError.unknownTool(name)
        }
        return try await PluginRegistry.shared.executeToolStreaming(
            pluginId: id,
            toolName: name,
            argumentsJSON: argumentsJSON,
            progressHandler: progressHandler
        )
    }

    private var hooksMap: [String: PluginHooks] {
        var map: [String: PluginHooks] = [:]
        for plugin in PluginRegistry.shared.registeredPlugins {
            if let hooks = PluginRegistry.shared.hooks(for: plugin.id) {
                map[plugin.id] = hooks
            }
        }
        return map
    }

    // MARK: - Streaming Implementation

    /// Parsed SSE event from the Copilot API.
    private enum SSEEvent: Sendable, CustomStringConvertible {
        case contentDelta(String)
        case thinkingDelta(String)
        case toolCallDelta(index: Int, id: String?, name: String?, arguments: String?)
        case usage(TokenUsage)
        case finish(reason: String)

        var description: String {
            switch self {
            case .contentDelta(let s): "contentDelta(\(s.prefix(50)))"
            case .thinkingDelta(let s): "thinkingDelta(\(s.prefix(50)))"
            case .toolCallDelta(let i, let id, let n, _): "toolCallDelta(idx=\(i), id=\(id ?? "nil"), name=\(n ?? "nil"))"
            case .usage(let u): "usage(prompt=\(u.promptTokens), completion=\(u.completionTokens))"
            case .finish(let r): "finish(\(r))"
            }
        }
    }

    private func streamCompletion(updatingAt index: Int, tools: [MCPTool]) async throws {
        // Try provider-based streaming first
        if let provider = resolveProvider() {
            try await streamWithProvider(provider, updatingAt: index, tools: tools)
            return
        }

        // Non-Copilot provider failed — don't silently fall back
        let activeId = providerRegistry?.activeProviderId ?? "github-copilot"
        if activeId != "github-copilot" {
            throw CopilotError.providerNotConfigured(activeId)
        }

        // Legacy fallback: direct Copilot API
        guard let token = authManager.token else {
            throw CopilotError.notAuthenticated
        }

        let model = settingsStore.selectedModel
        let stream: AsyncThrowingStream<SSEEvent, Error>

        // Merge plugin tools with MCP tools (filtered by access mode)
        let allTools: [MCPTool]
        let pluginTools = await PluginRegistry.shared.allTools(for: settingsStore.appMode)
        if settingsStore.toolAccessMode == .loadWhenNeeded && !tools.isEmpty {
            let discovered = tools.filter { discoveredMCPTools.contains($0.name) }
            allTools = pluginTools + discovered
        } else {
            allTools = pluginTools + tools
        }

        if Self.useResponsesAPI(model: model) {
            // Responses API path
            let (instructions, input) = buildResponsesInput(mcpTools: tools)
            let apiTools: [ResponsesAPITool]? = allTools.isEmpty ? nil : allTools.map { tool in
                ResponsesAPITool(type: "function", name: tool.name,
                                 description: tool.description, parameters: tool.inputSchema)
            }
            let reasoning: ResponsesReasoning? = {
                let m = model.lowercased()
                if m.hasPrefix("o1") || m.hasPrefix("o3") || m.hasPrefix("o4")
                    || m.hasPrefix("gpt-5") || m.hasPrefix("gpt-4") {
                    return ResponsesReasoning(effort: nil, summary: "auto")
                }
                return nil
            }()
            let request = ResponsesAPIRequest(
                model: model, instructions: instructions, input: input,
                stream: true, maxOutputTokens: maxOutputTokens, temperature: 0.7,
                tools: apiTools, toolChoice: apiTools != nil ? "auto" : nil,
                reasoning: reasoning
            )
            let requestData = try JSONEncoder().encode(request)
            let urlRequest = Self.buildURLRequest(
                url: URL(string: Self.responsesEndpoint)!, token: token, body: requestData,
                messages: buildAPIMessages(mcpTools: tools))
            stream = try await Self.openResponsesSSEStream(urlRequest: urlRequest)
        } else {
            // Chat Completions path
            let apiMessages = buildAPIMessages(mcpTools: tools)
            let apiTools = allTools.isEmpty ? nil : allTools.map { tool in
                APITool(type: "function", function: .init(
                    name: tool.name, description: tool.description, parameters: tool.inputSchema))
            }
            let effort = settingsStore.reasoningEffort
            let reasoningValue: String? = (ReasoningEffort.isSupported(model: model) && effort != .off)
                ? effort.rawValue : nil
            let request = ChatCompletionRequest(
                model: model, messages: apiMessages, stream: true,
                maxTokens: maxOutputTokens, temperature: 0.7, tools: apiTools,
                toolChoice: apiTools != nil ? "auto" : nil,
                streamOptions: .init(includeUsage: true),
                reasoningEffort: reasoningValue
            )
            let requestData = try JSONEncoder().encode(request)
            let urlRequest = Self.buildURLRequest(
                url: URL(string: Self.chatEndpoint)!, token: token, body: requestData,
                messages: apiMessages)
            stream = try await Self.openSSEStream(urlRequest: urlRequest)
        }

        // Event consumption — identical for both APIs
        var pendingToolCalls: [String: (id: String, name: String, arguments: String)] = [:]

        for try await event in stream {
            try Task.checkCancellation()

            switch event {
            case .contentDelta(let text):
                messages[index].content += text
                contentRevision &+= 1

            case .thinkingDelta(let text):
                if messages[index].reasoning == nil { messages[index].reasoning = "" }
                messages[index].reasoning! += text
                contentRevision &+= 1

            case .toolCallDelta(let idx, let id, let name, let arguments):
                let key = "\(idx)"
                if let id {
                    pendingToolCalls[key] = (id: id, name: name ?? "", arguments: "")
                }
                if let name, pendingToolCalls[key] != nil {
                    pendingToolCalls[key]?.name = name
                }
                if let arguments, pendingToolCalls[key] != nil {
                    pendingToolCalls[key]?.arguments += arguments
                }

            case .usage(let usage):
                tokenUsage = usage

            case .finish(let reason):
                messages[index].finishReason = ChatMessage.FinishReason(rawValue: reason)
                if reason == "tool_calls" {
                    let calls = pendingToolCalls.sorted(by: { $0.key < $1.key }).map { (_, value) in
                        ToolCall(id: value.id, function: .init(name: value.name, arguments: value.arguments))
                    }
                    messages[index].toolCalls = calls
                }
                return
            }
        }
    }

    // MARK: - Provider-Based Streaming

    private func streamWithProvider(_ provider: any LLMProvider, updatingAt index: Int, tools: [MCPTool]) async throws {
        let model = currentModelId
        // Merge built-in tools with MCP tools
        let allTools: [MCPTool]
        let pluginTools = await PluginRegistry.shared.allTools(for: settingsStore.appMode)
        let isAugment = providerRegistry?.activeProviderId == "augment"
        // Augment can't use tool_search effectively, so always send all MCP tools
        if settingsStore.toolAccessMode == .loadWhenNeeded && !tools.isEmpty && !isAugment {
            let discovered = tools.filter { discoveredMCPTools.contains($0.name) }
            allTools = pluginTools + discovered
        } else {
            allTools = pluginTools + tools
        }

        let apiMessages = buildAPIMessages(mcpTools: tools)
        let apiTools: [APITool]? = allTools.isEmpty ? nil : allTools.map { tool in
            APITool(type: "function", function: .init(
                name: tool.name, description: tool.description, parameters: tool.inputSchema))
        }

        // Use models.dev metadata — synchronous read from in-memory cache (no network hop)
        let activeId = providerRegistry?.activeProviderId ?? ""
        let mdProvider = providerRegistry?.modelsDevProviders[activeId]
        let modelInfo = mdProvider?.models[model]
        let npm = mdProvider?.npm

        let effort = settingsStore.reasoningEffort
        let supportsReasoning = ReasoningEffort.isSupported(
            model: model, modelInfo: modelInfo, npm: npm, providerId: activeId)
        let reasoningValue: String? = (supportsReasoning && effort != .off) ? effort.rawValue : nil

        // Model-specific temperature (from OpenCode transform.ts)
        // nil = don't send (some models like GPT-5.4 reject temperature param)
        // Only fall back to 0.7 if the model explicitly supports temperature
        let temp: Double? = ProviderTransform.temperature(modelId: model)
            ?? (modelInfo?.temperature == true ? 0.7 : nil)

        // Model-specific max output tokens
        let maxOut = ProviderTransform.maxOutputTokens(model: modelInfo, modelId: model)

        // Model-specific topP / topK (MiniMax, Gemini, Qwen)
        let topP = ProviderTransform.topP(modelId: model)
        let topK = ProviderTransform.topK(modelId: model)

        // Provider-specific extra fields (Z.AI thinking, Alibaba enable_thinking, GPT-5 reasoningSummary)
        let providerId = providerRegistry?.activeProviderId ?? ""
        let extraFields = ProviderTransform.extraRequestFields(
            modelId: model, model: modelInfo, npm: npm, providerId: providerId, effort: reasoningValue)

        let options = ProviderOptions(
            maxOutputTokens: maxOut,
            temperature: temp,
            topP: topP,
            topK: topK,
            reasoningEffort: reasoningValue,
            systemPrompt: systemInstructions,
            toolChoice: apiTools != nil ? "auto" : nil,
            extraFields: extraFields
        )

        let stream = provider.streamCompletion(
            messages: apiMessages, model: model, tools: apiTools, options: options)

        var pendingToolCalls: [String: (id: String, name: String, arguments: String)] = [:]

        for try await event in stream {
            try Task.checkCancellation()

            switch event {
            case .contentDelta(let text):
                messages[index].content += text
                contentRevision &+= 1

            case .thinkingDelta(let text):
                if messages[index].reasoning == nil { messages[index].reasoning = "" }
                messages[index].reasoning! += text
                contentRevision &+= 1

            case .toolCallStart(let idx, let id, let name):
                let key = "\(idx)"
                pendingToolCalls[key] = (id: id, name: name, arguments: "")

            case .toolCallDelta(let idx, let arguments):
                let key = "\(idx)"
                if pendingToolCalls[key] != nil {
                    pendingToolCalls[key]?.arguments += arguments
                }

            case .toolCallStop:
                break // Tool call assembly happens at finish

            case .usage(let usage):
                tokenUsage = usage

            case .finish(let reason):
                messages[index].finishReason = reason
                if reason == .toolCalls {
                    let calls = pendingToolCalls.sorted(by: { $0.key < $1.key }).map { (_, value) in
                        ToolCall(id: value.id, function: .init(name: value.name, arguments: value.arguments))
                    }
                    messages[index].toolCalls = calls
                }

                // Auto-generate title after first complete response
                if reason == .stop || reason == .toolCalls {
                    maybeGenerateTitle(provider: provider, model: model)
                }
                return

            case .error(let error):
                throw error
            }
        }
    }

    // MARK: - Auto Title Generation

    private func maybeGenerateTitle(provider: any LLMProvider, model: String) {
        // Only generate title once, after first user+assistant exchange
        guard autoGeneratedTitle == nil,
              titleGenerationTask == nil,
              messages.count >= 2,
              messages.contains(where: { $0.role == .user }),
              messages.contains(where: { $0.role == .assistant && !$0.content.isEmpty }) else { return }

        let firstUser = messages.first(where: { $0.role == .user })?.content ?? ""
        let firstAssistant = messages.first(where: { $0.role == .assistant && !$0.content.isEmpty })?.content ?? ""

        titleGenerationTask = Task {
            if let title = await TitleGenerator.generate(
                userMessage: firstUser,
                assistantPreview: firstAssistant,
                provider: provider,
                model: model
            ) {
                self.autoGeneratedTitle = title
            } else {
                self.autoGeneratedTitle = TitleGenerator.fallbackTitle(from: firstUser)
            }
        }
    }

    /// Build the URL request with headers matching OpenCode TS version.
    private static func buildURLRequest(
        url: URL, token: String, body: Data,
        messages: [APIMessage] = [],
        agentInitiated: Bool = false
    ) -> URLRequest {
        var urlRequest = URLRequest(url: url)
        urlRequest.httpMethod = "POST"
        urlRequest.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        urlRequest.setValue(userAgent, forHTTPHeaderField: "User-Agent")
        urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
        urlRequest.setValue("conversation-edits", forHTTPHeaderField: "Openai-Intent")

        let initiator = agentInitiated ? "agent"
            : (messages.last?.role != "user" ? "agent" : "user")
        urlRequest.setValue(initiator, forHTTPHeaderField: "x-initiator")

        urlRequest.httpBody = body
        return urlRequest
    }

    /// Open a validated byte stream — shared by both SSE parsers.
    private nonisolated static func validatedBytes(
        for request: URLRequest
    ) async throws -> URLSession.AsyncBytes {
        let (bytes, response) = try await urlSession.bytes(for: request)
        guard let http = response as? HTTPURLResponse else {
            throw CopilotError.invalidResponse
        }
        guard http.statusCode == 200 else {
            var body = ""
            for try await line in bytes.lines { body += line; if body.count > 2000 { break } }
            throw CopilotError.httpError(http.statusCode, body)
        }
        return bytes
    }

    /// Parse Chat Completions SSE stream into SSEEvent variants.
    private nonisolated static func openSSEStream(
        urlRequest: URLRequest
    ) async throws -> AsyncThrowingStream<SSEEvent, Error> {
        let bytes = try await validatedBytes(for: urlRequest)

        return AsyncThrowingStream { continuation in
            let task = Task.detached {
                do {
                    let decoder = JSONDecoder()
                    var finishedReason: String?

                    for try await line in bytes.lines {
                        try Task.checkCancellation()

                        guard line.hasPrefix("data: ") else { continue }
                        let payload = String(line.dropFirst(6))

                        if payload == "[DONE]" { break }

                        guard let data = payload.data(using: .utf8),
                              let chunk = try? decoder.decode(StreamChunk.self, from: data) else { continue }

                        if let usage = chunk.usage {
                            continuation.yield(.usage(usage))
                        }

                        if finishedReason != nil { continue }

                        guard let choice = chunk.choices?.first else { continue }

                        if let content = choice.delta.content {
                            continuation.yield(.contentDelta(content))
                        }

                        if let reasoning = choice.delta.reasoningContent ?? choice.delta.reasoningText {
                            continuation.yield(.thinkingDelta(reasoning))
                        }

                        if let toolCallDeltas = choice.delta.toolCalls {
                            for delta in toolCallDeltas {
                                continuation.yield(.toolCallDelta(
                                    index: delta.index,
                                    id: delta.id,
                                    name: delta.function?.name,
                                    arguments: delta.function?.arguments
                                ))
                            }
                        }

                        if let finishReason = choice.finishReason {
                            finishedReason = finishReason
                        }
                    }

                    if let reason = finishedReason {
                        continuation.yield(.finish(reason: reason))
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    private static let defaultContextWindow = 128_000
    private static let outputTokenMax = 32_000

    /// Dynamic output token limit: min(model's max_output_tokens, 32k).
    /// Always sends a concrete value — matches OpenCode TS behavior.
    private var maxOutputTokens: Int {
        if let limit = selectedModelInfo?.capabilities?.limits?.maxOutputTokens {
            return min(limit, Self.outputTokenMax)
        }
        return Self.outputTokenMax
    }

    /// Max chars for historical (non-current-turn) tool results sent to the API.
    private static let maxHistoricalToolResultChars = 200

    private func preparedMessages() -> (messages: [ChatMessage], answeredToolCallIds: Set<String>, currentTurnToolIds: Set<String>) {
        var msgs = messages
        if let summaryId = summaryMessageId,
           let summaryIndex = msgs.firstIndex(where: { $0.id == summaryId }) {
            msgs = Array(msgs[summaryIndex...])
        }
        let answered = Set(msgs.compactMap { $0.role == .tool ? $0.toolCallId : nil })

        // Find the last assistant message that issued tool calls — those are "current turn" results.
        var currentIds = Set<String>()
        for msg in msgs.reversed() {
            if let calls = msg.toolCalls, !calls.isEmpty {
                currentIds = Set(calls.map(\.id))
                break
            }
        }
        return (msgs, answered, currentIds)
    }

    /// Truncate a tool result that belongs to a previous turn.
    private static func truncateHistoricalToolResult(_ content: String) -> String {
        guard let idx = content.index(content.startIndex,
                                      offsetBy: maxHistoricalToolResultChars,
                                      limitedBy: content.endIndex) else { return content }
        return String(content[..<idx]) + "\n[…truncated]"
    }

    /// Resolve tool message content, truncating historical results.
    private static func resolvedToolContent(_ content: String, callId: String?, currentTurnToolIds: Set<String>) -> String {
        if let id = callId, currentTurnToolIds.contains(id) { return content }
        return truncateHistoricalToolResult(content)
    }

    func buildAPIMessages(mcpTools: [MCPTool] = []) -> [APIMessage] {
        let (messagesToProcess, answeredToolCallIds, currentTurnToolIds) = preparedMessages()

        var apiMessages: [APIMessage] = [
            APIMessage(role: "system", content: systemInstructions)
        ]
        if let notice = deferredToolsNotice(mcpTools: mcpTools) {
            apiMessages.append(APIMessage(role: "system", content: notice))
        }

        for msg in messagesToProcess {
            switch msg.role {
            case .system:
                continue
            case .user:
                if let imageData = msg.imageData {
                    var parts: [APIContentPart] = []
                    if !msg.content.isEmpty { parts.append(.text(msg.content)) }
                    parts.append(.imageURL(imageData.jpegBase64DataURL))
                    apiMessages.append(APIMessage(role: "user", content: nil, contentParts: parts))
                } else {
                    apiMessages.append(APIMessage(role: "user", content: msg.content))
                }
            case .assistant:
                // Summary message is sent as user role to provide context
                if msg.id == summaryMessageId {
                    apiMessages.append(APIMessage(role: "user", content: msg.content))
                    continue
                }
                if let toolCalls = msg.toolCalls, !toolCalls.isEmpty {
                    // Only include tool calls that have corresponding results
                    let answeredCalls = toolCalls.filter { answeredToolCallIds.contains($0.id) }
                    if !answeredCalls.isEmpty {
                        let apiToolCalls = answeredCalls.map {
                            APIToolCall(id: $0.id, type: "function", function: .init(name: $0.function.name, arguments: $0.function.arguments))
                        }
                        apiMessages.append(APIMessage(
                            role: "assistant",
                            content: msg.content.isEmpty ? nil : msg.content,
                            toolCalls: apiToolCalls,
                            reasoning: msg.reasoning
                        ))
                    } else if !msg.content.isEmpty {
                        apiMessages.append(APIMessage(
                            role: "assistant",
                            content: msg.content,
                            reasoning: msg.reasoning
                        ))
                    }
                } else if !msg.content.isEmpty || msg.reasoning != nil {
                    apiMessages.append(APIMessage(
                        role: "assistant",
                        content: msg.content.isEmpty ? nil : msg.content,
                        reasoning: msg.reasoning
                    ))
                }
            case .tool:
                let content = Self.resolvedToolContent(msg.content, callId: msg.toolCallId, currentTurnToolIds: currentTurnToolIds)
                if let imageData = msg.imageData {
                    let parts: [APIContentPart] = [.text(content), .imageURL(imageData.jpegBase64DataURL)]
                    apiMessages.append(APIMessage(role: "tool", content: nil, toolCallId: msg.toolCallId, contentParts: parts))
                } else {
                    apiMessages.append(APIMessage(role: "tool", content: content, toolCallId: msg.toolCallId))
                }
            }
        }

        return apiMessages
    }

    // MARK: - Responses API Input Builder

    func buildResponsesInput(mcpTools: [MCPTool] = []) -> (instructions: String, input: [ResponsesInputItem]) {
        let (messagesToProcess, answeredToolCallIds, currentTurnToolIds) = preparedMessages()

        var instructions = systemInstructions
        // Responses API only supports a single instructions field, so append here
        if let notice = deferredToolsNotice(mcpTools: mcpTools) {
            instructions += "\n\n" + notice
        }
        var input: [ResponsesInputItem] = []

        for msg in messagesToProcess {
            switch msg.role {
            case .system:
                continue
            case .user:
                input.append(.userMessage(content: msg.content, imageData: msg.imageData))
            case .assistant:
                if msg.id == summaryMessageId {
                    input.append(.userMessage(content: msg.content))
                    continue
                }
                if !msg.content.isEmpty {
                    input.append(.assistantMessage(content: msg.content))
                }
                if let toolCalls = msg.toolCalls {
                    for call in toolCalls where answeredToolCallIds.contains(call.id) {
                        input.append(.functionCall(
                            callId: call.id, name: call.function.name,
                            arguments: call.function.arguments
                        ))
                    }
                }
            case .tool:
                if let callId = msg.toolCallId {
                    var output = Self.resolvedToolContent(msg.content, callId: callId, currentTurnToolIds: currentTurnToolIds)
                    // Responses API function_call_output is text-only; append image reference if available
                    if let imageData = msg.imageData {
                        output += "\n\n![screenshot](\(imageData.jpegBase64DataURL))"
                    }
                    input.append(.functionCallOutput(callId: callId, output: output))
                }
            }
        }
        return (instructions, input)
    }

    // MARK: - Responses API SSE Stream

    /// Parse Responses API SSE stream (typed events) into the same SSEEvent variants.
    private nonisolated static func openResponsesSSEStream(
        urlRequest: URLRequest
    ) async throws -> AsyncThrowingStream<SSEEvent, Error> {
        let bytes = try await validatedBytes(for: urlRequest)

        return AsyncThrowingStream { continuation in
            let task = Task.detached {
                do {
                    let decoder = JSONDecoder()
                    var currentEventType: String?
                    var hasToolCalls = false

                    for try await line in bytes.lines {
                        try Task.checkCancellation()

                        if line.hasPrefix("event: ") {
                            currentEventType = String(line.dropFirst(7))
                            continue
                        }

                        guard line.hasPrefix("data: "),
                              let eventType = currentEventType else { continue }
                        let payload = String(line.dropFirst(6))
                        currentEventType = nil

                        guard let data = payload.data(using: .utf8) else { continue }

                        switch eventType {
                        case "response.output_text.delta":
                            if let evt = try? decoder.decode(ResponsesStreamEvent.self, from: data),
                               let delta = evt.delta {
                                continuation.yield(.contentDelta(delta))
                            }

                        case "response.reasoning_text.delta",
                             "response.reasoning_summary_text.delta":
                            if let evt = try? decoder.decode(ResponsesStreamEvent.self, from: data),
                               let delta = evt.delta {
                                continuation.yield(.thinkingDelta(delta))
                            }

                        case "response.output_item.added":
                            if let evt = try? decoder.decode(ResponsesStreamEvent.self, from: data),
                                let item = evt.item, item.type == "function_call" {
                                let idx = evt.outputIndex ?? 0
                                hasToolCalls = true
                                continuation.yield(.toolCallDelta(
                                    index: idx, id: item.callId, name: item.name, arguments: nil
                                ))
                            }

                        case "response.function_call_arguments.delta":
                            if let evt = try? decoder.decode(ResponsesStreamEvent.self, from: data) {
                                let idx = evt.outputIndex ?? 0
                                continuation.yield(.toolCallDelta(
                                    index: idx, id: nil, name: nil, arguments: evt.delta
                                ))
                            }

                        case "response.completed":
                            if let evt = try? decoder.decode(ResponsesStreamEvent.self, from: data),
                               let usage = evt.response?.usage {
                                continuation.yield(.usage(usage.asTokenUsage))
                            }
                            continuation.yield(.finish(reason: hasToolCalls ? "tool_calls" : "stop"))

                        case "response.failed":
                            continuation.yield(.finish(reason: "error"))

                        case "response.incomplete":
                            continuation.yield(.finish(reason: "length"))

                        default:
                            break
                        }
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    // MARK: - Compaction

    private var systemInstructions: String {
        let prompt = settingsStore.effectiveSystemPrompt
        return prompt.isEmpty ? SettingsStore.defaultSystemPrompt : prompt
    }

    /// Returns a separate system message listing undiscovered MCP tools, or nil if not applicable.
    private func deferredToolsNotice(mcpTools: [MCPTool]) -> String? {
        guard settingsStore.toolAccessMode == .loadWhenNeeded, !mcpTools.isEmpty else { return nil }
        let undiscovered = mcpTools.filter { !discoveredMCPTools.contains($0.name) }
        guard !undiscovered.isEmpty else { return nil }
        let toolList = undiscovered.map { "- \($0.name): \($0.description)" }.joined(separator: "\n")
        return "The following MCP tools are available but not yet loaded. Use the tool_search tool to load them before calling:\n\(toolList)"
    }

    // MARK: - Message Management

    func deleteMessage(_ id: UUID) {
        guard let index = messages.firstIndex(where: { $0.id == id }) else { return }
        let msg = messages[index]
        // Clean up tool call statuses for removed message
        if let calls = msg.toolCalls {
            for call in calls {
                toolCallStatuses.removeValue(forKey: call.id)
                toolCallServerNames.removeValue(forKey: call.id)
            }
        }
        messages.remove(at: index)
        if summaryMessageId == id { summaryMessageId = nil }
    }

    private static var summarizerInstructions: String { AgentConfig.summarizer.systemPrompt }
    private static var summarizerPrompt: String { AgentConfig.summarizerPrompt }

    func compactConversation() async throws {
        // Try provider-based compaction first
        if let provider = resolveProvider() {
            try await compactWithProvider(provider)
            return
        }

        // Legacy fallback: direct Copilot API
        guard let token = authManager.token else { throw CopilotError.notAuthenticated }

        let model = settingsStore.selectedModel
        let isResponses = Self.useResponsesAPI(model: model)
        let requestData: Data
        let url: URL

        if isResponses {
            let (_, input) = buildResponsesInput()
            var fullInput = input
            fullInput.append(.userMessage(content: Self.summarizerPrompt))
            let request = ResponsesAPIRequest(
                model: model, instructions: Self.summarizerInstructions,
                input: fullInput, stream: false,
                maxOutputTokens: 4096, temperature: 0.5,
                tools: nil, toolChoice: nil, reasoning: nil
            )
            requestData = try JSONEncoder().encode(request)
            url = URL(string: Self.responsesEndpoint)!
        } else {
            var apiMessages = buildAPIMessages()
            if !apiMessages.isEmpty && apiMessages[0].role == "system" {
                apiMessages[0] = APIMessage(role: "system", content: Self.summarizerInstructions)
            }
            apiMessages.append(APIMessage(role: "user", content: Self.summarizerPrompt))
            let request = ChatCompletionRequest(
                model: model, messages: apiMessages, stream: false,
                maxTokens: 4096, temperature: 0.5,
                tools: nil, toolChoice: nil, streamOptions: nil,
                reasoningEffort: nil
            )
            requestData = try JSONEncoder().encode(request)
            url = URL(string: Self.chatEndpoint)!
        }

        let urlRequest = Self.buildURLRequest(url: url, token: token, body: requestData, agentInitiated: true)

        let (data, response) = try await Self.urlSession.data(for: urlRequest)
        guard let http = response as? HTTPURLResponse, http.statusCode == 200 else {
            let body = String(data: data, encoding: .utf8) ?? ""
            throw CopilotError.httpError((response as? HTTPURLResponse)?.statusCode ?? 0, body)
        }

        let summaryText: String?
        let usage: TokenUsage?

        if isResponses {
            let result = try JSONDecoder().decode(NonStreamingResponsesResponse.self, from: data)
            summaryText = result.output.first?.content?.first(where: { $0.type == "output_text" })?.text
            usage = result.usage?.asTokenUsage
        } else {
            let result = try JSONDecoder().decode(NonStreamingResponse.self, from: data)
            summaryText = result.choices.first?.message.content
            usage = result.usage
        }

        guard let text = summaryText, !text.isEmpty else { return }
        let summaryMessage = ChatMessage(role: .assistant, content: text)
        messages.append(summaryMessage)
        summaryMessageId = summaryMessage.id
        if let usage { tokenUsage = usage }
    }

    // MARK: - Provider-Based Compaction

    private func compactWithProvider(_ provider: any LLMProvider) async throws {
        let model = currentModelId
        var apiMessages = buildAPIMessages()
        if !apiMessages.isEmpty && apiMessages[0].role == "system" {
            apiMessages[0] = APIMessage(role: "system", content: AgentConfig.summarizer.systemPrompt)
        }
        apiMessages.append(APIMessage(role: "user", content: AgentConfig.summarizerPrompt))

        let options = ProviderOptions(
            maxOutputTokens: AgentConfig.summarizer.maxOutputTokens,
            temperature: AgentConfig.summarizer.temperature,
            systemPrompt: AgentConfig.summarizer.systemPrompt,
            agentInitiated: true
        )

        let response = try await provider.sendCompletion(
            messages: apiMessages, model: model, tools: nil, options: options)

        guard let text = response.content, !text.isEmpty else { return }
        let summaryMessage = ChatMessage(role: .assistant, content: text)
        messages.append(summaryMessage)
        summaryMessageId = summaryMessage.id
        if let usage = response.usage { tokenUsage = usage }
    }

    // MARK: - Fetch Models

    func fetchModels() async {
        guard let token = authManager.token else { return }

        var request = URLRequest(url: URL(string: Self.modelsEndpoint)!)
        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")
        request.setValue(Self.userAgent, forHTTPHeaderField: "User-Agent")
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.cachePolicy = .reloadIgnoringLocalAndRemoteCacheData

        do {
            let (data, response) = try await Self.urlSession.data(for: request)
            guard let http = response as? HTTPURLResponse, http.statusCode == 200 else { return }

            let modelsResponse = try JSONDecoder().decode(ModelsResponse.self, from: data)
            // Deduplicate by model ID (API may return duplicates like gpt-4)
            var seen = Set<String>()
            let unique = modelsResponse.data.filter { seen.insert($0.id).inserted }
            availableModels = unique.sorted { $0.id < $1.id }
            // Overlay Copilot API's actual limits onto models.dev data
            providerRegistry?.overlayCopilotLimits(from: unique)
        } catch {
            // Non-critical
        }
    }

    // MARK: - Errors

    enum CopilotError: LocalizedError {
        case notAuthenticated
        case invalidResponse
        case httpError(Int, String)
        case providerNotConfigured(String)

        var errorDescription: String? {
            switch self {
            case .notAuthenticated: "Not authenticated. Please sign in to GitHub."
            case .invalidResponse: "Invalid response from server."
            case .httpError(let code, let body): "HTTP \(code): \(body)"
            case .providerNotConfigured(let id): "Provider \"\(id)\" is not configured. Check your API key in Settings."
            }
        }
    }
}
